export type StatusClass = '1xx' | '2xx' | '3xx' | '4xx' | '5xx';

export interface StatusCodeEntry {
  code: number;
  name: string;
  statusClass: StatusClass;
  description: string;
  commonUse: string;
  rfc: string;
  rfcUrl: string;
  note?: string;
}

export const CLASS_LABELS: Record<StatusClass, string> = {
  '1xx': 'Informational',
  '2xx': 'Success',
  '3xx': 'Redirection',
  '4xx': 'Client Error',
  '5xx': 'Server Error',
};

export const STATUS_CODES: StatusCodeEntry[] = [
  {
    code: 100,
    name: 'Continue',
    statusClass: '1xx',
    description: 'The server has received the request headers and the client should proceed to send the request body.',
    commonUse: 'Sent before a large request body, so the client only uploads it once the server confirms it will accept the request.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.2.1',
  },
  {
    code: 101,
    name: 'Switching Protocols',
    statusClass: '1xx',
    description: 'The server agrees to switch protocols as requested by the client, most commonly to upgrade the connection to WebSocket.',
    commonUse: 'Returned when a WebSocket handshake or another Upgrade header negotiation succeeds.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.2.2',
  },
  {
    code: 102,
    name: 'Processing',
    statusClass: '1xx',
    description: 'The server has accepted the request but has not yet completed it, and no final response is available yet.',
    commonUse: 'Used by WebDAV servers on long running requests to stop the client from timing out while it waits.',
    rfc: 'RFC 2518',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc2518',
  },
  {
    code: 103,
    name: 'Early Hints',
    statusClass: '1xx',
    description: 'The server sends preliminary headers before the final response so the browser can start acting on them early.',
    commonUse: 'Lets a page start preloading linked stylesheets, scripts or fonts while the server is still preparing the full response.',
    rfc: 'RFC 8297',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc8297',
  },
  {
    code: 104,
    name: 'Upload Resumption Supported',
    statusClass: '1xx',
    description: 'The server confirms it supports resumable uploads for the request that follows, so an interrupted upload can continue later.',
    commonUse: 'Returned before accepting a large file upload, letting the client resume from where a dropped connection left off.',
    rfc: 'draft-ietf-httpbis-resumable-upload-05',
    rfcUrl: 'https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/05/',
    note: 'Temporary registration, expires 2026-11-13',
  },
  {
    code: 200,
    name: 'OK',
    statusClass: '2xx',
    description: 'The request has succeeded and the response body, if any, contains the requested resource or result.',
    commonUse: 'The default success response for GET, PUT and POST requests that complete normally.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.1',
  },
  {
    code: 201,
    name: 'Created',
    statusClass: '2xx',
    description: 'The request succeeded and a new resource was created as a result, usually returned with a Location header.',
    commonUse: 'Returned by a POST request that creates a new record, such as a new user or order.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.2',
  },
  {
    code: 202,
    name: 'Accepted',
    statusClass: '2xx',
    description: 'The request has been accepted for processing, but the processing has not completed yet.',
    commonUse: 'Returned by asynchronous jobs or queues that acknowledge a request before doing the actual work.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.3',
  },
  {
    code: 203,
    name: 'Non-Authoritative Information',
    statusClass: '2xx',
    description: 'The request succeeded, but the returned metadata came from a local or third-party copy rather than the origin server.',
    commonUse: 'Returned by a proxy or cache that modified response headers before forwarding a successful response.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.4',
  },
  {
    code: 204,
    name: 'No Content',
    statusClass: '2xx',
    description: 'The request succeeded, but there is no content to return in the response body.',
    commonUse: 'Returned by a successful DELETE or an update request where the client does not need a response body.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.5',
  },
  {
    code: 205,
    name: 'Reset Content',
    statusClass: '2xx',
    description: 'The request succeeded and the client should reset the document view that caused the request to be sent.',
    commonUse: 'Used after a form submission to tell the browser to clear the form fields.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.6',
  },
  {
    code: 206,
    name: 'Partial Content',
    statusClass: '2xx',
    description: 'The server is delivering only part of the resource in response to a Range header sent by the client.',
    commonUse: 'Returned when streaming or resuming downloads of video, audio or large files.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.7',
  },
  {
    code: 207,
    name: 'Multi-Status',
    statusClass: '2xx',
    description: 'The response body contains multiple independent status codes for the different parts of a batch operation.',
    commonUse: 'Used by WebDAV when a single request affects multiple resources, each with its own outcome.',
    rfc: 'RFC 4918',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc4918',
  },
  {
    code: 208,
    name: 'Already Reported',
    statusClass: '2xx',
    description: 'The members of a WebDAV binding have already been listed in a previous part of the same multi status response, so they are not repeated.',
    commonUse: 'Avoids duplicate entries when a WebDAV collection is enumerated more than once in one response.',
    rfc: 'RFC 5842',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc5842',
  },
  {
    code: 226,
    name: 'IM Used',
    statusClass: '2xx',
    description: 'The server has fulfilled a request for the resource and the response is a representation of the result of one or more instance manipulations.',
    commonUse: 'Used with delta encoding, where the response is a diff applied on top of a previously fetched version.',
    rfc: 'RFC 3229',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc3229',
  },
  {
    code: 300,
    name: 'Multiple Choices',
    statusClass: '3xx',
    description: 'The request has more than one possible response and the client or user should choose one of them.',
    commonUse: 'Returned when a server offers several representations of a resource, such as different file formats.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.1',
  },
  {
    code: 301,
    name: 'Moved Permanently',
    statusClass: '3xx',
    description: 'The requested resource has been permanently moved to a new URL given in the Location header.',
    commonUse: 'Used for permanent URL redirects, such as after a domain change, so search engines update their index.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.2',
  },
  {
    code: 302,
    name: 'Found',
    statusClass: '3xx',
    description: 'The requested resource has been temporarily moved to a different URL, and the client should keep using the original URL for future requests.',
    commonUse: 'Used for temporary redirects, such as sending a user to a login page before returning them to the original page.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.3',
  },
  {
    code: 303,
    name: 'See Other',
    statusClass: '3xx',
    description: 'The response to the request can be found under a different URL and should be retrieved with a GET request.',
    commonUse: 'Used to redirect the browser to a confirmation page after a form is submitted, preventing an accidental resubmission.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.4',
  },
  {
    code: 304,
    name: 'Not Modified',
    statusClass: '3xx',
    description: 'The resource has not changed since the version specified by the request headers, so the client should use its cached copy.',
    commonUse: 'Returned when a browser revalidates a cached asset and the server confirms nothing has changed.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.5',
  },
  {
    code: 305,
    name: 'Use Proxy',
    statusClass: '3xx',
    description: 'The requested resource must be accessed through the proxy given in the response.',
    commonUse: 'Deprecated due to security concerns and no longer used by modern clients.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.6',
    note: 'Deprecated',
  },
  {
    code: 306,
    name: 'Unused',
    statusClass: '3xx',
    description: 'This status code was used in an earlier version of the HTTP specification and is no longer used.',
    commonUse: 'Reserved by the specification but not returned by any server.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.7',
    note: 'Reserved, not used',
  },
  {
    code: 307,
    name: 'Temporary Redirect',
    statusClass: '3xx',
    description: 'The requested resource is temporarily at a different URL, and the client must repeat the request with the same method.',
    commonUse: 'Used like 302 but guarantees the request method and body are preserved, such as for a POST that must stay a POST.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.8',
  },
  {
    code: 308,
    name: 'Permanent Redirect',
    statusClass: '3xx',
    description: 'The requested resource has permanently moved, and the client must repeat the request with the same method at the new URL.',
    commonUse: 'Used like 301 but guarantees the request method and body are preserved during the redirect.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.9',
  },
  {
    code: 400,
    name: 'Bad Request',
    statusClass: '4xx',
    description: 'The server cannot process the request because of a client error, such as malformed syntax or invalid request data.',
    commonUse: 'Returned when required fields are missing, JSON fails to parse, or input fails validation.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.1',
  },
  {
    code: 401,
    name: 'Unauthorized',
    statusClass: '4xx',
    description: 'The request requires valid authentication credentials, and none were provided or the ones provided are invalid.',
    commonUse: 'Returned when a user must log in or provide a valid token before accessing a protected resource.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.2',
  },
  {
    code: 402,
    name: 'Payment Required',
    statusClass: '4xx',
    description: 'Reserved for future use, originally intended for digital payment systems.',
    commonUse: 'Occasionally reused by APIs to indicate a usage quota or subscription payment is required.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.3',
  },
  {
    code: 403,
    name: 'Forbidden',
    statusClass: '4xx',
    description: 'The server understood the request but refuses to authorize it, regardless of the credentials provided.',
    commonUse: 'Returned when a logged in user tries to access a resource their account does not have permission for.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.4',
  },
  {
    code: 404,
    name: 'Not Found',
    statusClass: '4xx',
    description: 'The server cannot find the requested resource. The requested URL may be misspelled or the resource may have been removed.',
    commonUse: 'Returned when a webpage is missing, moved, or the URL is incorrect.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.5',
  },
  {
    code: 405,
    name: 'Method Not Allowed',
    statusClass: '4xx',
    description: 'The request method is known by the server but is not supported for the target resource.',
    commonUse: 'Returned when a client sends a DELETE or PUT to an endpoint that only accepts GET or POST.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.6',
  },
  {
    code: 406,
    name: 'Not Acceptable',
    statusClass: '4xx',
    description: 'The server cannot produce a response matching the list of acceptable formats given in the request headers.',
    commonUse: 'Returned when a client requests a content type through the Accept header that the server does not support.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.7',
  },
  {
    code: 407,
    name: 'Proxy Authentication Required',
    statusClass: '4xx',
    description: 'The client must authenticate itself with a proxy before the request can proceed.',
    commonUse: 'Returned by a proxy server that requires credentials before forwarding traffic.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.8',
  },
  {
    code: 408,
    name: 'Request Timeout',
    statusClass: '4xx',
    description: 'The server timed out waiting for the request from the client.',
    commonUse: 'Returned when a client opens a connection and takes too long to send a complete request.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.9',
  },
  {
    code: 409,
    name: 'Conflict',
    statusClass: '4xx',
    description: 'The request conflicts with the current state of the target resource.',
    commonUse: 'Returned when two clients try to update the same resource at once, or a unique field already exists.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.10',
  },
  {
    code: 410,
    name: 'Gone',
    statusClass: '4xx',
    description: 'The requested resource is no longer available and has been permanently removed, with no forwarding address.',
    commonUse: 'Used instead of 404 when a resource was intentionally and permanently deleted.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.11',
  },
  {
    code: 411,
    name: 'Length Required',
    statusClass: '4xx',
    description: 'The server refuses to accept the request without a defined Content Length header.',
    commonUse: 'Returned when a client streams a request body without specifying its length in advance.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.12',
  },
  {
    code: 412,
    name: 'Precondition Failed',
    statusClass: '4xx',
    description: 'One of the conditions in the request headers, such as If Match, evaluated to false on the server.',
    commonUse: 'Used for optimistic concurrency control, rejecting an update when the resource has changed since it was last read.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.13',
  },
  {
    code: 413,
    name: 'Content Too Large',
    statusClass: '4xx',
    description: 'The request body is larger than the server is willing or able to process.',
    commonUse: 'Returned when a file upload or request payload exceeds the server configured size limit.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.14',
  },
  {
    code: 414,
    name: 'URI Too Long',
    statusClass: '4xx',
    description: 'The URI requested by the client is longer than the server is willing to interpret.',
    commonUse: 'Returned when too much data is packed into a query string instead of the request body.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.15',
  },
  {
    code: 415,
    name: 'Unsupported Media Type',
    statusClass: '4xx',
    description: 'The request body format is not supported by the server for the requested method and resource.',
    commonUse: 'Returned when a client sends XML to an API that only accepts JSON, or an unsupported file type.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.16',
  },
  {
    code: 416,
    name: 'Range Not Satisfiable',
    statusClass: '4xx',
    description: 'The range specified by the Range header cannot be fulfilled, usually because it falls outside the size of the resource.',
    commonUse: 'Returned when a client resumes a download using a byte range that no longer matches the file.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.17',
  },
  {
    code: 417,
    name: 'Expectation Failed',
    statusClass: '4xx',
    description: 'The expectation given in the request Expect header could not be met by the server.',
    commonUse: 'Returned when a client sends an Expect: 100-continue header that the server cannot satisfy.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.18',
  },
  {
    code: 418,
    name: 'Unused',
    statusClass: '4xx',
    description: 'Originally defined as a joke response for coffee pots that refuse to brew coffee, now formally reserved and unused.',
    commonUse: 'Reserved by the specification but not returned by any conformant server.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.19',
    note: 'Reserved, not used',
  },
  {
    code: 421,
    name: 'Misdirected Request',
    statusClass: '4xx',
    description: 'The request was directed at a server that is not able to produce a response for the combination of scheme and authority in the request URI.',
    commonUse: 'Returned by HTTP/2 servers when a connection was reused for a domain it is not authoritative for.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.20',
  },
  {
    code: 422,
    name: 'Unprocessable Content',
    statusClass: '4xx',
    description: 'The request is well formed, but the server was unable to process the contained instructions due to semantic errors.',
    commonUse: 'Returned by APIs when JSON parses correctly but individual field values fail validation.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.21',
  },
  {
    code: 423,
    name: 'Locked',
    statusClass: '4xx',
    description: 'The resource being accessed is locked and cannot currently be modified.',
    commonUse: 'Used by WebDAV when a file or collection is checked out or locked by another client.',
    rfc: 'RFC 4918',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc4918',
  },
  {
    code: 424,
    name: 'Failed Dependency',
    statusClass: '4xx',
    description: 'The request failed because it depended on another request that failed.',
    commonUse: 'Used by WebDAV when one operation in a batch fails, causing dependent operations to be skipped.',
    rfc: 'RFC 4918',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc4918',
  },
  {
    code: 425,
    name: 'Too Early',
    statusClass: '4xx',
    description: 'The server is unwilling to risk processing a request that might be replayed.',
    commonUse: 'Returned to reject early data sent over a TLS 1.3 0-RTT connection before the handshake is confirmed.',
    rfc: 'RFC 8470',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc8470',
  },
  {
    code: 426,
    name: 'Upgrade Required',
    statusClass: '4xx',
    description: 'The server refuses to perform the request using the current protocol and requires the client to upgrade.',
    commonUse: 'Returned when a server requires the connection to switch to a newer protocol, such as TLS or HTTP/2.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.22',
  },
  {
    code: 428,
    name: 'Precondition Required',
    statusClass: '4xx',
    description: 'The origin server requires the request to be conditional, typically to prevent lost updates.',
    commonUse: 'Returned to force clients to use If Match headers so concurrent edits do not silently overwrite each other.',
    rfc: 'RFC 6585',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc6585',
  },
  {
    code: 429,
    name: 'Too Many Requests',
    statusClass: '4xx',
    description: 'The client has sent too many requests in a given amount of time and is being rate limited.',
    commonUse: 'Returned by an API when a client exceeds its rate limit, often with a Retry After header.',
    rfc: 'RFC 6585',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc6585',
  },
  {
    code: 431,
    name: 'Request Header Fields Too Large',
    statusClass: '4xx',
    description: 'The server refuses to process the request because its header fields are too large.',
    commonUse: 'Returned when cookies or custom headers grow too large for the server to accept.',
    rfc: 'RFC 6585',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc6585',
  },
  {
    code: 451,
    name: 'Unavailable For Legal Reasons',
    statusClass: '4xx',
    description: 'The server is denying access to the resource as a result of a legal demand.',
    commonUse: 'Returned when content is blocked due to a court order, censorship law or takedown notice.',
    rfc: 'RFC 7725',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc7725',
  },
  {
    code: 500,
    name: 'Internal Server Error',
    statusClass: '5xx',
    description: 'The server encountered an unexpected condition that prevented it from fulfilling the request.',
    commonUse: 'The generic response for an unhandled exception or bug in server side code.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.1',
  },
  {
    code: 501,
    name: 'Not Implemented',
    statusClass: '5xx',
    description: 'The server does not support the functionality required to fulfill the request.',
    commonUse: 'Returned when a request uses a method or feature the server has not implemented.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.2',
  },
  {
    code: 502,
    name: 'Bad Gateway',
    statusClass: '5xx',
    description: 'The server, acting as a gateway or proxy, received an invalid response from the upstream server.',
    commonUse: 'Returned by a reverse proxy or load balancer when the backend server it forwards to is failing or misbehaving.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.3',
  },
  {
    code: 503,
    name: 'Service Unavailable',
    statusClass: '5xx',
    description: 'The server is temporarily unable to handle the request, usually due to maintenance or overload.',
    commonUse: 'Returned during planned maintenance windows or when a server is overloaded and shedding traffic.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.4',
  },
  {
    code: 504,
    name: 'Gateway Timeout',
    statusClass: '5xx',
    description: 'The server, acting as a gateway or proxy, did not receive a timely response from the upstream server.',
    commonUse: 'Returned by a proxy or load balancer when the backend server takes too long to respond.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.5',
  },
  {
    code: 505,
    name: 'HTTP Version Not Supported',
    statusClass: '5xx',
    description: 'The server does not support the HTTP protocol version used in the request.',
    commonUse: 'Returned when a client sends a request using an HTTP version the server cannot handle.',
    rfc: 'RFC 9110',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.6',
  },
  {
    code: 506,
    name: 'Variant Also Negotiates',
    statusClass: '5xx',
    description: 'The server has an internal configuration error where the chosen variant resource is itself set up for content negotiation.',
    commonUse: 'Indicates a server misconfiguration in transparent content negotiation setups.',
    rfc: 'RFC 2295',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc2295',
  },
  {
    code: 507,
    name: 'Insufficient Storage',
    statusClass: '5xx',
    description: 'The server is unable to store the representation needed to complete the request.',
    commonUse: 'Used by WebDAV servers when the underlying storage has run out of space.',
    rfc: 'RFC 4918',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc4918',
  },
  {
    code: 508,
    name: 'Loop Detected',
    statusClass: '5xx',
    description: 'The server terminated an operation because it detected an infinite loop while processing the request.',
    commonUse: 'Used by WebDAV when a binding configuration would otherwise cause the server to process the same request forever.',
    rfc: 'RFC 5842',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc5842',
  },
  {
    code: 510,
    name: 'Not Extended',
    statusClass: '5xx',
    description: 'Further extensions to the request are required for the server to fulfill it.',
    commonUse: 'Historic status for policy based extension negotiation, now obsoleted and rarely implemented.',
    rfc: 'RFC 2774',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc2774',
    note: 'Obsoleted',
  },
  {
    code: 511,
    name: 'Network Authentication Required',
    statusClass: '5xx',
    description: 'The client needs to authenticate to gain network access, typically enforced by a captive portal.',
    commonUse: 'Returned by public Wi Fi networks that require the user to log in or accept terms before browsing.',
    rfc: 'RFC 6585',
    rfcUrl: 'https://www.rfc-editor.org/rfc/rfc6585',
  },
];

const STATUS_CODE_MAP = new Map(STATUS_CODES.map((entry) => [entry.code, entry]));

export function findStatusCode(code: number): StatusCodeEntry | undefined {
  return STATUS_CODE_MAP.get(code);
}

export function statusClassOf(code: number): StatusClass {
  return `${Math.floor(code / 100)}xx` as StatusClass;
}
